### ISSUE TITLE
Add ledger support for baking and endorsing

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#104]
Add support for using a Ledger hardware wallet, running the Tezos Baking ledger app, for baking.

Source code for the ledger apps (both regular wallet and baking app) is available here: https://github.com/obsidiansystems/ledger-app-tezos

The Tezos client already supports ledger integration directly, but there is value and demand to support the ledger in Signatory, and use the remote signer capability of the tezos-client instead.

The Ledger device can have two "apps" installed, the regular wallet, that can sign any operation, but it prompts the user for approvals, and the Baker app, that only signs endorsements and blocks (and possibly ballots??). To install the baker app, use the Ledger Live Desktop app, and enable experimental mode. Then go to manager and search for Tezos. You should see two options as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/1114943/89572571-2283dc80-d7de-11ea-95ff-bef19cd8513f.png)

## Related resources:

https://medium.com/@obsidian.systems/tezos-baking-v2-0-0-for-the-ledger-nano-s-testing-tezos-amendment-proposals-c10aced06824
https://www.tezos.org.sg/guide-to-using-the-tezos-node/
TestPad Scripts for Signatory: https://ecadlabs.ontestpad.com/project/23/

**Comment by michaelkernaghan** [comment]
added to the "related resources" section

**Comment by jevonearth** [comment]
Closing issue, this feature has been implemented and shipped. We actively bake on testnets with ledgers.
