### ISSUE TITLE
ARM Binaries

### ISSUE THREAD

**Issue by Xelendor1** [ecadlabs/signatory#116]
Would you mind adding ARM docker container or Binaries to the release?

Thanks

**Comment by Xelendor1** [comment]
Just wondering if there was an update on this. I'm currently working on a project to create "the worlds most secure and eco-friendly budget baker".  Having this support arm would be amazing

**Comment by yazdan** [comment]
Hi @Xelendor1 
I think this is as easy as running following command:
`GOOS=linux GOARCH=arm64 make`
replace `GOOS` and `GOARCH` with one of the values from this commands results
`go tool dist list`

**Comment by jevonearth** [comment]
We publish x86 and ARM binaries for Windows, Linux and MacOS. You can choose which architecture to download from the Assets section of each release on the Github Releases page: https://github.com/ecadlabs/signatory/releases
