### ISSUE TITLE
Replicating the animal-mnemonics ledger ID from Octez

### ISSUE THREAD

**Issue by AbineshECAD** [ecadlabs/signatory#168]
Ocaml source: https://gitlab.com/tezos/tezos/-/blob/master/src/lib_signer_backends/unix/ledger_names.ml
Unit test Ocaml source: https://gitlab.com/tezos/tezos/-/blob/master/src/lib_signer_backends/unix/test/test_crouching.ml

**Comment by AbineshECAD** [comment]
Draft PR: https://github.com/ecadlabs/signatory/pull/164

The above code does not give the same animal-adjective names as the Ocaml code. The same array of animal names and adjective names is used.
The same Blake2b library is used for SHA hashing. But it doesn't seem like we get the same hash for the unit test input "1234".
The hash output is converted into uint64 bit integer and the value is not sam either.
The next step is to get the remainder by dividing it with the adjective/animal array size, which obviously didn't result in the same output as the Ocaml code.

**Comment by michaelkernaghan** [comment]
done
