### ISSUE TITLE
No error displayed when config.yaml file not found

### ISSUE THREAD

**Issue by AbineshECAD** [ecadlabs/signatory#189]
https://ecadlabs.slack.com/archives/CL1NK8526/p1653529935135909
![image](https://user-images.githubusercontent.com/82827388/170461078-ac7a889e-0e18-4203-a906-3c9816db7ee4.png)

**Comment by alexzbusko** [comment]
Verified that an error message is coming back from YAML file not being found:
```
$ ./signatory-cli list -c something.yaml
Error: open something.yaml: no such file or directory
```

Also command is now returning a non-zero exit code
