### ISSUE TITLE
Add support for signing 0x05 / "Michelson Data" aka: failing noop operation 

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#192]
[The `florence` Tezos protocol introduced a new `0x05` magic byte for "Michelson data". ](https://tezos.gitlab.io/protocols/009_florence.html#new-failing-noop-operation)This is a op type used for signing arbitrary data that can (or should) never be accidentally or maliciously applied as a real Tezos operation. 

https://www.ledger.com/academy/school-of-block/blind-signing-the-crypto-attack-vector-you-must-be-aware-of#

A `failing_noop` operation can be used to mitigate blind signing attacks. More context on the attack can be found here https://hackmd.io/@marigold-dev/HJWHdQ_09 and  

TODO:

- Add 0x05 to `tezos/message.go`
- Add `failing_noop` to `config/TezosPolicy>AllowedOperations`
- Add tests.
- Update documentation

Example data:

`0x05010000004254657a6f73205369676e6564204d6573736167653a206d79646170702e636f6d20323032312d30312d31345431353a31363a30345a2048656c6c6f20776f726c6421`

Testing using `tezos-client`. Assuming tezos-client has an account with name alias `sig_test_account` that points to a running signatory instance.

`tezos-client sign bytes 0x05 for octez_signer_local_key`

`tezos-client sign bytes "0x05010000004254657a6f73205369676e6564204d6573736167653a206d79646170702e636f6d20323032312d30312d31345431353a31363a30345a2048656c6c6f20776f726c6421" for octez_signer_local_key`

**Comment by Sths-neo** [comment]
Hello, when will this be added ? It would be super useful for our project :)

**Comment by jevonearth** [comment]
Hi @Sths-neo, 

We are planning to have this included in a release by the end of August. Thanks for letting us know! :)

**Comment by Sths-neo** [comment]
Great news! Thank you so much

**Comment by jevonearth** [comment]
Hello @Sths-neo 

Can you try using our new `v0.3.3-beta-rc0` release? This should include the ability to sign `failing_noop` operations. Be sure to include `failing_noop` in your config. Thank you!

**Comment by aBMania** [comment]
Hey, i'm working with @Sths-neo on this. 
Just tested it, but got an error:

```
time="2022-08-22T13:46:09Z" level=info msg="Public Key Hash:    tz1MBNfBnNn8fZCJVrrXV95FSgyuUxbmt3Mm"
time="2022-08-22T13:46:09Z" level=info msg="Vault:              File"
time="2022-08-22T13:46:09Z" level=info msg="ID:                 oracle2"
time="2022-08-22T13:46:09Z" level=info msg="Active:             true"
time="2022-08-22T13:46:09Z" level=info msg="Allowed Operations: [block endorsement generic]"
time="2022-08-22T13:46:09Z" level=info msg="Allowed Kinds:      [endorsement failing_noop transaction]"

...

time="2022-08-22T13:47:18Z" level=error msg="tezos: unknown watermark tag: 5" pkh=tz1MBNfBnNn8fZCJVrrXV95FSgyuUxbmt3Mm raw=05020000016807040a00000016000010e5b01d33b207f177185342d8206cf72086eb3d07070094a6c7ba4b07070001070700010a0000001601f3cc49599c4854ca655a347691d749cd70b2e7a40007040a0000001600001797a2cd215e3c7280784e090d17051fdc4a9bf307070094a6c7ba4b07070001070700010a0000001601f3cc49599c4854ca655a347691d749cd70b2e7a40007040a000000160000551cd56708ce084c402d141e23bac7bb512ce9f907070094a6c7ba4b07070001070700010a0000001601f3cc49599c4854ca655a347691d749cd70b2e7a40007040a0000001600008b2924aa7f98a52b4cdd844dabc7c3cf086c80f607070094a6c7ba4b07070001070700010a0000001601f3cc49599c4854ca655a347691d749cd70b2e7a40007040a000000160000acbab8c7a6aa0436f7990a25199f48eeba5cf30507070094a6c7ba4b07070001070700010a0000001601f3cc49599c4854ca655a347691d749cd70b2e7a400
```

Version: 
```sh
> signatory version
Release Version: 0.3.3-beta-rc0
```

Am i doing something wrong?

**Comment by danielelisi** [comment]
Hello @Sths-neo and @aBMania 

We just published a new RC for Signatory which correctly signs `failing_noop` operations. You can find the latest RC release here https://github.com/ecadlabs/signatory/releases/tag/v0.3.3-beta-rc1

You'll also need to add `failing_noop` to the list of `allowed_operations` in your Signatory config file.
