### ISSUE TITLE
Public facing grafana dashboard for testnet signatory bakers

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#200]
We want to make our testnet signatory instance metrics visible to the public. For our testnet signatories, setup a grafana dashboard that shows up status/signing latency/errors for the testnet bakers. We can link this from the baker page that is mentioned in issue #113

**Comment by BGMurphy** [comment]
While creating a dashboard for Signatory, I ran into a couple metrics that don't appear to be working, as well as a couple that may be useful to add.  
Broken metrics:

- vault_sign_request_error_total
- signing_ops_total

Both of these were giving incorrect values in previous versions of signatory, and aren't working at all in the newest version.  

Possible metrics to add:
- Backend request latency
- Client to signatory latency
- Health metric
- Signatory version

**Comment by BGMurphy** [comment]
The dashboard is now available at https://grafana.ecadinfra.com/public-dashboards/b8a1f18696f640d3bf025c243dc12f67?orgId=1

**Comment by danielelisi** [comment]
> > The dashboard is now available at https://grafana.ecadinfra.com/public-dashboards/b8a1f18696f640d3bf025c243dc12f67?orgId=1
> 
> Is this dashboard public? Or only in a limited-access Grafana?

There was a misconfiguration from our end. Now the dashboard is public again. Thanks for pointing that out @zikarad
