### ISSUE TITLE
Signatory errors out with "invalid boolean value: 2" since the switch to Jakarta

### ISSUE THREAD

**Issue by Mayeu** [ecadlabs/signatory#205]
Hello,

We are running a test signatory setup as part of our baking stack [on testnet](https://ghostnet.tzkt.io/tz3cpZyzsqEMk5RGHYL7m7obnLFtq7LxvCLA/schedule), and since the switch to Jakarta we have the following error in our log when trying to sign a block: `msg="invalid boolean value: 2"`.

As you can see in the previous link, the baker missed all the blocks since the 28th ~19h (time at which that network switched to Jakarta), checking the log of Signatory, there are errors for all of them.

Full log line example (with raw data):
```
Jun 28 17:07:30 signatory-z1kh signatory[1305]: time="2022-06-28T17:07:30Z" level=error msg="invalid boolean value: 2" pkh=tz3cpZyzsqEMk5RGHYL7m7obnLFtq7LxvCLA raw=11af1864d9000bb28703a4852fc6cc0ecde11c599941651e4a532197a48c084e2f5b75a9a8b643534e910000000062bb3552042c39b4d080c1575898d04ce9494a92f01dc383741a5386892d73fbf1c3b07bcc00000021000000010200000004000bb2870000000000000004ffffffff00000004000000014d33938f492722277f1d2f9a63e797c5c5b207dec6120859fe4384107fe6352daafc5d3c600812134143c1be015d89a906264547aff9f2ea3026908f82d5139e00000001cb9f439e19d500000002
```

Any idea what could be happening, or how I could dig more info about this?

**Comment by PizBernina** [comment]
We have the same error on mainnent but only for assigned blocks. Endorsement work for us.

**Comment by PizBernina** [comment]
Similar to this issues it seems https://github.com/ecadlabs/signatory/issues/204

**Comment by PizBernina** [comment]
@Mayeu we restarted signatory and now we successfully do blocks again. Will monitor further.

**Comment by zikarad** [comment]
It looks like the "--liquidity-baking... pass" is the issue. Switching to "on" seems to solve the signing!
@Mayeu Could you confirm?

**Comment by Mayeu** [comment]
@zikarad: ho, I won't be able to report before tomorrow. We only managed the signer part, the baker running is delegated to a third party who is on the other side of the planet 😅. I'll contact them to see about this, and will report back later on.

**Comment by AbineshECAD** [comment]
@Mayeu So did signatory found a bug ? 😅

**Comment by michaelkernaghan** [comment]
I recreated the issue here, thanks
```
Jun 29 08:22:45.513 - 013-PtJakart.baker.actions:   ledger_bip (tz1XGwK6kkiJaq2ZEJYcWEj5Tc8bcV6pNHqV)
Jun 29 08:22:56.009 - 013-PtJakart.baker.actions: Voting pass for liquidity baking toggle vote
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling: error while baking
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:   Error:
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:     Rpc request failed:
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:        - meth: POST
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:        - uri: http://localhost:6732/keys/tz1XGwK6kkiJaq2ZEJYcWEj5Tc8bcV6pNHqV
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:        - error: Oops! It looks like we forged an invalid HTTP request.
Jun 29 08:22:56.094 - 013-PtJakart.baker.scheduling:                   [{"id":"failure","kind":"temporary","msg":"invalid boolean value: 2"}]
```

and change to on it works again:
```
Jun 29 08:26:21.904 - 013-PtJakart.baker.actions:   ledger_bip (tz1XGwK6kkiJaq2ZEJYcWEj5Tc8bcV6pNHqV)
Jun 29 08:26:33.003 - 013-PtJakart.baker.actions: Voting on for liquidity baking toggle vote
Jun 29 08:26:35.011 - 013-PtJakart.baker.actions: block BKjhuCzXQbxvZiaVW1ra6Y6PWNebYcMQjhLUqVHeZKbzao17o54 at level 344016,
```

and off fails with error about boolean value 1 :
```
Jun 29 08:34:48.004 - 013-PtJakart.baker.actions: Voting off for liquidity baking toggle vote
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling: error while baking
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:   Error:
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:     Rpc request failed:
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:        - meth: POST
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:        - uri: http://localhost:6732/keys/tz1XGwK6kkiJaq2ZEJYcWEj5Tc8bcV6pNHqV
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:        - error: Oops! It looks like we forged an invalid HTTP request.
Jun 29 08:34:48.104 - 013-PtJakart.baker.scheduling:                   [{"id":"failure","kind":"temporary","msg":"invalid boolean value: 1"}]
```

**Comment by jevonearth** [comment]
Hi All,

We have a release candidate with binary builds and docker images available here:

https://github.com/ecadlabs/signatory/releases/tag/v0.3.1-beta-rc0

Docker images are;

`docker pull ecadlabs/signatory:v0.3.1-beta-rc0-amd64`
`docker pull ecadlabs/signatory:v0.3.1-beta-rc0-arm64`

Based on our testing, these work with the liquidity baking toggle set to on/off/pass

**Comment by Mayeu** [comment]
Everything is working OK from our side since this fix 👍
