### ISSUE TITLE
in the example config file for signatory the list of allowed_operations is missing 'preendorsement'

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/signatory#211]
1. open the example config file for signatory
2.  the list of allowed_operations is missing 'preendorsement'

 '# List of [generic, block, endorsement]'

should be

' # List of [generic, block, endorsement, preendorsement]'

**Comment by AbineshECAD** [comment]
Done as part of https://github.com/ecadlabs/signatory/pull/185

**Comment by michaelkernaghan** [comment]
closed as part of #185
