### ISSUE TITLE
A vault implementation should only return or work with known key types

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#215]
In Tezos, and in Signatory, we only deal with three key curves;

tz1 - [Ed25519](https://ed25519.cr.yp.to/)
tz2 - [Secp256k1](https://en.bitcoin.it/wiki/Secp256k1) aka: P256K
tz3 - P-256

Vault backends may contain keys of other types, such as AWS KMS may have a `P-384` key.

Signatory attempts to list all keys when it starts up and matches available keys to keys configured in the signatory yaml config file.

The `listPublicKeys` implementation could check each key returned and skip unsupported curve types. Presently the three types are listed above but note that that list could likely grow as Tezos evolves.

**Comment by AbineshECAD** [comment]
Update the documents about this change.
