### ISSUE TITLE
Set up double baking tests

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/signatory#245]
Signatory is made to not allow double baking when using it as a signing backend. We need to figure out a way to set up signatory to create a double baking scenario and that is what this issue is all about. I don't really know how to go about setting this up so any notes on setup should be recorded here or in another form of documentation

**Comment by michaelkernaghan** [comment]
To set up double baking, first set up two ghost nets installations and get each working with its own key and signatory installation using ledger devices.

Then, import the key from ledger B to machine A, and set B up to bake on A. then B will be double baking.

**Comment by danielelisi** [comment]
Using Ledger devices isn't strictly required for this, we can use the `file` backend for the test. 

Now that I'm getting comfortable with using Tezos sandbox local networks I will try double baking on this setup.

**Comment by stephengaudet** [comment]
[doublebake.zip](https://github.com/ecadlabs/signatory/files/12589377/doublebake.zip)

there is a readme in this zip file explaining how to use the docker compose file also in the zip. it sets up double baking scenario with flextesa
