### ISSUE TITLE
No tezos-client information in getting started page

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/signatory#263]
Since the user will need information that the tezos-client can provide for creating secret keys that signatory will use we need to put that into the getting started section. We say file-based storage is unsecure and then want other methods to be used and some of these require a key import but we never mention how to create these keys. Mostly the import is done for the GCP and YubiHSM backends so they should be the focus of this

One of the things that should be a part of this is helping the user navigate the created directories that tezos-client makes to access the public/secret keys

**Comment by michaelkernaghan** [comment]
this was covered in another issue where detailed pages for azure and yubi were added
