### ISSUE TITLE
`signatory-cli import` command should support local file vault

### ISSUE THREAD

**Issue by danielelisi** [ecadlabs/signatory#265]
Trying to import a secret key to a local key vault returns an error

```
$ signatory-cli -c /etc/signatory/config.yml import --vault local_file_keys <secret_key>

Error: import: vault local_file_keys doesn't support import operation
```

We should implement this functionality for importing keys to local file vaults

**Comment by AbineshECAD** [comment]
https://github.com/ecadlabs/signatory/pull/308

This issue will be monitored, and import functionality will be added to the file vault if needed.
