### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#29]
Counters and histograms for;
* signing operations
* labels
  * vault
  * vault_name
  * op
  * opkind
* errors
  * backend error types (azure, use http codes? 401,403 etc...)

Create a companion grafana dashboard to help operators make the most of these metrics easily
Documentation on use, prometheus quickstart config snippets

**Comment by AbineshECAD** [comment]
@AbineshECAD Test and close if works as specified.

**Comment by stephengaudet** [comment]
signatory response code (2xx, 4xx, 5xx)
--done with #306 

signatory duration round trip
--to do, currently only exposing vault time, need time between signatory receipt of request and send of response

operation type & kind
--done

chain_id
-- can be added as a label on existing metrics 

(possibly) protocol hash (short)
-- can be added as a label on existing metrics

**Comment by jevonearth** [comment]
Closing as done.

signatory duration round trip - we don't have a strong need for this metric, so we will remove it from the scope.
