### ISSUE TITLE
YubiHSM support

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#32]
Add YubiHSM support

**Comment by gaia** [comment]
What does _evaluating_ mean? It's in Alpha or Beta state? Can it be used for production, with caveats?

**Comment by jevonearth** [comment]
Hi @gaia 

YubiHSM2 support is complete and available in the master branch, and we are in the process of testing it on alphanet for general baking operations. We also have more documentation to write, and we will then be doing a public release.

If you're interested in trying it out, we can help you with setup. All feedback is welcome and appreciated.

**Comment by gaia** [comment]
I will help you try it out. Any hope it will be compatible with TRD? https://github.com/habanoz/tezos-reward-distributor/issues/77

**Comment by jevonearth** [comment]
Based on what I read there, I think it should work! I'll try find some time to test this out.
