### ISSUE TITLE
jwt password rotation facility not accepting new password

### ISSUE THREAD

**Issue by stephengaudet** [ecadlabs/signatory#371]
steps to reproduce: 

1.configure a JWT password rotation scenario like this: 
`  jwt:
   users:
    username1:
      password: password1
      secret: .sEtcU5RwLQYsA5qQ1c6zpo3FljQxfAKP
      jwt_exp: 20
      old_cred_exp: 100
      new_data:
        password: password2
        secret: ..sEtcU5RwLQYsA5qQ1c6zpo3FljQxfAKP
        jwt_exp: 21`

2.login with username1 and password2

expected: 
the new password is accepted (both old and new accepted until old expires, then just new) 

actual: 
the login returns 401 when the new password is used

**Comment by AbineshECAD** [comment]
@stephengaudet Fixed in this commit [new and old user cred accepted in parallel till the exp time](https://github.com/ecadlabs/signatory/pull/367/commits/0b286d7797f90ba3106dd1bb02e436ad13ca14fa)

**Comment by stephengaudet** [comment]
looks good, thank you
