### ISSUE TITLE
jwt credential expiry renews after signatory restart

### ISSUE THREAD

**Issue by stephengaudet** [ecadlabs/signatory#373]
the JWT credential configuration contains an optional field `Exp: 60` where the value is number of minutes. 
the shortcoming is the datatype in which the expiry is expressed, number of minutes. this means the credentials expire some number of minutes after Signatory start time.  should Signatory get restarted before the password rotation configuration is removed from the config file, the expiry window is renewed. 

steps to reproduce: 
1.configure a password rotation where the old creds expire in 1 minute.
2.start signatory
3.immediately use old credentials
4.immediately stop signatory
5.repeat steps 2-4 ad infinitum (the old credentials will work forever)

expected:
the user should be able to configure a static date time in UTC at which point the old credentials expire

actual: 
because the expiry is a number of minutes, restarting signatory resets the expiration

**Comment by AbineshECAD** [comment]
@stephengaudet Fixed this as part of this commit: [old expiry logic change](https://github.com/ecadlabs/signatory/pull/367/commits/505d0e530f62cd5934c1493efabe12fcf557287a)

**Comment by stephengaudet** [comment]
fixed for v1.1.0 release
