### ISSUE TITLE
Signatory 1.1.0 using GCP HSM don't start anymore when there are destroyed key

### ISSUE THREAD

**Issue by Mayeu** [ecadlabs/signatory#383]
Hello,

The last version of Signatory (1.1.0) doesn't start anymore when the first key available in GCP HSM is destroyed.

We are in a situation where our mainnet baking keyring contains two keys:
<img width="873" alt="Screenshot 2023-06-29 at 08 44 02" src="https://github.com/ecadlabs/signatory/assets/222375/aee6fbbd-5eed-4f14-acf4-3ba827f33767">

The first one only contains one version that has been destroyed since we had an issue during our initial key generation ceremony:
<img width="858" alt="Screenshot 2023-06-29 at 08 44 25" src="https://github.com/ecadlabs/signatory/assets/222375/80bebaf7-ce5f-48bf-ab2f-9b5b4c6a97c4">

The second one contains our current active key:
<img width="858" alt="Screenshot 2023-06-29 at 08 44 36" src="https://github.com/ecadlabs/signatory/assets/222375/fedb76be-59f4-4977-8421-3394aaf1d660">

It seems that some of the [changes between 1.0.0-beta3 and 1.1.0](https://github.com/ecadlabs/signatory/compare/v1.0.0-beta3...v1.1.0) broke the key selection logic. I see that  the external library used to interact with cloudKMS has been upgraded, and that the [cloudKMSIterator](https://github.com/ecadlabs/signatory/compare/v1.0.0-beta3...v1.1.0#diff-248428148d1d13d2089ed7c40e481495f3be21e4002bc132e50a907f30a987a9) function got changed as well.

When starting signatory we get the following error message:
```
Jun 29 06:20:34 signatory-WWWW signatory[1186]: {"level":"info","msg":"Initializing vault","time":"2023-06-29T06:20:34Z","vault":"cloudkms","vault_name":"kms"}
Jun 29 06:20:35 signatory-WWWW signatory[1186]: Error: (CloudKMS/projects/XXXXXXXXXX/locations/global/keyRings/YYYYYYY) getPublicKey: rpc error: code = FailedPrecondition desc = projects/XXXXXXXXXX/locations/global/keyRings/YYYYYYY/cryptoKeys/signatory-imported-2ZZZZZZZZZZZZZZZZZZZZ6/cryptoKeyVersions/1 is not enabled, current state is: DESTROYED.
Jun 29 06:20:35 signatory-WWWW signatory[1186]: error details: name = PreconditionFailure type = KEY_DESTROYED subj = projects/XXXXXXXXXX/locations/global/keyRings/YYYYYYY/cryptoKeys/signatory-imported-2ZZZZZZZZZZZZZZZZZZZZ6/cryptoKeyVersions/1 desc =
```

Beside the upgrade of Signatory, there was no other configuration changes on our side between those two versions.

Happy to provide more details if you need anything else.

**Comment by stephengaudet** [comment]
thank you for taking the time to communicate this issue to us @Mayeu 
I'm able to reproduce the issue you describe and a fix should be made soon.

**Comment by Mayeu** [comment]
Thank you @stephengaudet, if you need me to try out the PR before merging just warn me, I can do that on monday.

**Comment by stephengaudet** [comment]
thank you for the assistance @Mayeu but I went ahead and merged the fix to main.  Signatory integration tests now have a key in GCP with only destroyed key, so, I merged the fix in order to keep our builds passing. 
you may want to stay on v1.0.0-beta for another short time while I test the fix for another new issue https://github.com/ecadlabs/signatory/issues/379

I expect to make a new release v1.1.1 shortly that will have fixes for both this issue you've raised, and #379 

thank you kindly

**Comment by stephengaudet** [comment]
good day @Mayeu , Signatory v1.1.1 has been released and fixes this issue. thank you for letting us know.  please do let me know if v1.1.1 fixes the startup failure.

**Comment by Mayeu** [comment]
@stephengaudet thank you for warning me. I won't be able to test it out before the 17th, but I'll definitely warn you as soon as I have tested it :+1:

**Comment by Mayeu** [comment]
Hello @stephengaudet, I can confirm that the v1.1.1 solves our issue :+1:

Thank you ✨
