### ISSUE TITLE
signatory-cli list-ops out of date

### ISSUE THREAD

**Issue by stephengaudet** [ecadlabs/signatory#425]
steps to reproduce:
1. run `./signatory-cli list-ops`

expected:
the current set of supported operations are listed. they are: `{"activate_account", "ballot", "dal_attestation", "dal_publish_slot_header", "delegation",
		"double_baking_evidence", "double_endorsement_evidence", "double_preendorsement_evidence", "drain_delegate",
		"endorsement", "event", "failing_noop", "increase_paid_storage", "origination", "preendorsement", "proposals",
		"register_global_constant", "reveal", "sc_rollup_add_messages", "sc_rollup_cement",
		"sc_rollup_execute_outbox_message", "sc_rollup_originate", "sc_rollup_publish", "sc_rollup_recover_bond",
		"sc_rollup_refute", "sc_rollup_timeout", "seed_nonce_revelation", "set_deposits_limit", "transaction",
		"transfer_ticket", "update_consensus_key", "vdf_revelation", "zk_rollup_origination", "zk_rollup_publish", "zk_rollup_update"}`

actual:
Possible operation types:
    - activate_account
    - ballot
    - delegation
    - double_baking_evidence
    - double_endorsement_evidence
    - double_preendorsement_evidence
    - drain_delegate
    - endorsement
    - endorsement_with_slot
    - failing_noop
    - increase_paid_storage
    - origination
    - preendorsement
    - proposals
    - register_global_constant
    - reveal
    - seed_nonce_revelation
    - set_deposits_limit
    - transaction
    - update_consensus_key
    - vdf_revelation

**Comment by michaelkernaghan** [comment]
As of October 2024 the list is now ```Possible operation types:
    - activate_account
    - attestation
    - attestation_with_dal
    - ballot
    - dal_publish_commitment
    - delegation
    - double_attestation_evidence
    - double_baking_evidence
    - double_preattestation_evidence
    - drain_delegate
    - failing_noop
    - increase_paid_storage
    - origination
    - preattestation
    - proposals
    - register_global_constant
    - reveal
    - seed_nonce_revelation
    - set_deposits_limit
    - signature_prefix
    - smart_rollup_add_messages
    - smart_rollup_cement
    - smart_rollup_execute_outbox_message
    - smart_rollup_originate
    - smart_rollup_publish
    - smart_rollup_recover_bond
    - smart_rollup_refute
    - smart_rollup_timeout
    - transaction
    - transfer_ticket
    - update_consensus_key
    - vdf_revelation
    - zk_rollup_origination
    - zk_rollup_publish
    - zk_rollup_update```
    -
