### ISSUE TITLE
Log op/kind bytes in case where either are not recognized

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#43]
If a signing request is received, and signatory does not recognize the `kind` or `op` signatory should log an error including the actual bytes that are unrecognized.

By logging the unrecognized op/kind, we inform the signatory operator in diagnosing the issue.

**Comment by AbineshECAD** [comment]
@AbineshECAD Test this and close the issue if done.

**Comment by jevonearth** [comment]
To test manually, take a curl command, bump up the first bytes (In this case I made them `99`), and obseve the error in logs;

`curl -v -XPOST -d '"997a06a770e6cebe5b3e39483a13ac35f998d650e8b864696e31520922c7242b88c8d2ac55000003eb6d"' localhost:6732/keys/tz1Wk1Wdczh5BzyZ1uz2DW9xdFg9B5cFuGFm`

```
ERRO[0076] tezos: unknown watermark tag: 153             pkh=tz1Wk1Wdczh5BzyZ1uz2DW9xdFg9B5cFuGFm raw=997a06a770e6cebe5b3e39483a13ac35f998d650e8b864696e31520922c7242b88c8d2ac55000003eb6d
ERRO[0076] Error signing request: tezos: unknown watermark tag: 153
INFO[0076] POST /keys/tz1Wk1Wdczh5BzyZ1uz2DW9xdFg9B5cFuGFm  duration="73.445µs" hostname="localhost:6733" method=POST path=/keys/tz1Wk1Wdczh5BzyZ1uz2DW9xdFg9B5cFuGFm start_time="2022-06-03T07:13:58-07:00" status=400
```

TODO:
- Error message isn't great, should be more informative and actionable
- Write a test for this case.

**Comment by jevonearth** [comment]
Implemented.
