### ISSUE TITLE
Use promteheus histogram for vault_sign_request_duration_microseconds

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#44]
Convert the existing metric for `vault_sign_request_duration_microseconds` to a histogram.

Current metrics presents as follows;

```
vault_sign_request_duration_microseconds_sum{vault="Yubi"} 83.59501900000001
vault_sign_request_duration_microseconds_count{vault="Yubi"} 1
```

Please also add the `vault_name` label for the new histogram metric.

**Comment by e-asphyx** [comment]
Summaries are not recommended for a new code if I understand Prometheus doc correctly
