### ISSUE TITLE
(spike) Investigate support for YubiKeys as a HSM (Not YubiHSM)

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#57]
While doing a technical review with yubico staff, they told us we could support YubiKeys as a HSM for users that only have two or three keys. 

It would work a bit differently to the yubiHSM support. It's an interesting idea, as the cost of a yubikey is far less than a yubiHSM. It is also a lot cheaper than a Ledger device. Making it an attractive & inexpensive HSM solution for small bakers. The Yubkikey arguably has a better form factor than a ledger for this type of use.

Some unknowns;

* Does the YubiKey require human interaction for signings? (endorsements, bakes)
* Does the YubiKey require human intervention when powered on?
* What would provisioning of the key for this type of use look like?
* What would private key import look like?
* What would integration with the yubikey look like?

**Comment by AbineshECAD** [comment]
@jevonearth Is this done?

**Comment by jevonearth** [comment]
We did not validate this in depth, but I don't think it is viable, because my understanding is such that the yubikey cannot sign data unless a user touches the conductive button on the device, which would mean that the yubikey can not operate in an unattended mode.

**Comment by jevonearth** [comment]
Closing, as we have not seen demand for this, and we have doubts on it being possible to run such a configuration in an unattended mode.
