### ISSUE TITLE
Add `-v`/`--version` flags to all commands

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#81]
Add flag to print version and build info to the `signatory` and `signatory-cli` commands.

Testing/verifcation note;

The output from the `version` flag should be consistent with the `signatory_build_info` prometheus build metric.

**Comment by jevonearth** [comment]
Should be addressed by #179
Needs to be tested.

**Comment by jevonearth** [comment]
@AbineshECAD to add the version flag to the `signatory` binary also.

**Comment by AbineshECAD** [comment]
For signatory binary: https://github.com/ecadlabs/signatory/pull/202

**Comment by jevonearth** [comment]
Implemented.
