### ISSUE TITLE
Error signing request: xxxx is not listed in config

### ISSUE THREAD

**Issue by Twente-Mining** [ecadlabs/signatory#86]
Hi

After setting Signatory up (with Azure) 
I'm getting the following error: 

`Error signing request: xxxx is not listed in config
`

I can get the pubkey hash using curl
`curl 127.0.0.1:6733/keys/***`

Am I missing something?

**Comment by crmn111** [comment]
I have the same issue, can someone comment on this ?

**Comment by jevonearth** [comment]
Hi there. Pardon the slow response.

You need to list your public key hash in the `tezos:` list. This is separate from the `vaults:` section.

As seen on line 37 of the sample configuration here: https://github.com/ecadlabs/signatory/blob/master/signatory.yaml#L37

Let me know if you continue to have challenges. Thank you!

**Comment by jevonearth** [comment]
Closing this ticket. Let us know if you need more help!
